workflows:
  android-build:
    name: Android Build Workflow
    # Remove unnecessary description and extra fields
    environment:
      flutter: stable # If you're using Flutter, you can keep this line, otherwise remove it
    scripts:
      - name: Set up Android SDK
        script: |
          sdkmanager --install "platform-tools" "platforms;android-33" "build-tools;33.0.2"
          echo "SDK setup complete"
      
      - name: Build the APK
        script: |
          ./gradlew assembleDebug
