workflows:
  android-build:
    name: Android Build Workflow
    description: Build the APK for the BluetoothGyroMouse project
    environment:
      flutter: stable
      android: true
      gradle: true
      xcode: latest
    scripts:
      - name: Set up Android SDK
        script: |
          sdkmanager --install "platform-tools" "platforms;android-33" "build-tools;33.0.2"
          echo "SDK setup complete"

      - name: Build the APK
        script: |
          ./gradlew assembleDebug
        artifacts:
          - app/build/outputs/apk/debug/app-debug.apk
